//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberRecognizer.Cloud.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetworkDataModelContainer : DbContext
    {
        public NetworkDataModelContainer()
            : base("name=NetworkDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Network> NetworkSet { get; set; }
        public virtual DbSet<TrainingImageData> TrainingImageDataSet { get; set; }
        public virtual DbSet<TrainLog> TrainLogSet { get; set; }
        public virtual DbSet<PatternFitness> PatternFitnessSet { get; set; }
    }
}
