//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberRecognizerCloud.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternFitness
    {
        public int Id { get; set; }
        public string Pattern { get; set; }
        public double Fitness { get; set; }
    
        public virtual TrainLog TrainLog { get; set; }
    }
}
