//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberRecognizerCloud.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainLog
    {
        public TrainLog()
        {
            this.PatternFitnessSet = new HashSet<PatternFitness>();
        }
    
        public int TrainLogId { get; set; }
        public int GenerationNr { get; set; }
        public string MultipleGenPoolIdentifier { get; set; }
        public double Fitness { get; set; }
    
        public virtual Network Network { get; set; }
        public virtual ICollection<PatternFitness> PatternFitnessSet { get; set; }
    }
}
