//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace NumberRecognizer.App.NumberRecognizerService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NetworkInfo", Namespace="http://schemas.datacontract.org/2004/07/NumberRecognizer.Cloud.Contract.Data")]
    public partial class NetworkInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool CalculatedField;
        
        private System.Nullable<System.DateTime> CalculationEndField;
        
        private System.Nullable<System.DateTime> CalculationStartField;
        
        private NumberRecognizer.App.NumberRecognizerService.FitnessLog FinalPoolFitnessLogField;
        
        private bool MultipleGenPoolField;
        
        private System.Collections.Generic.Dictionary<string, NumberRecognizer.App.NumberRecognizerService.FitnessLog> MultiplePoolFitnessLogField;
        
        private double NetworkFitnessField;
        
        private int NetworkIdField;
        
        private string NetworkNameField;
        
        private NumberRecognizer.App.NumberRecognizerService.NetworkStatusType StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Calculated {
            get {
                return this.CalculatedField;
            }
            set {
                if ((this.CalculatedField.Equals(value) != true)) {
                    this.CalculatedField = value;
                    this.RaisePropertyChanged("Calculated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CalculationEnd {
            get {
                return this.CalculationEndField;
            }
            set {
                if ((this.CalculationEndField.Equals(value) != true)) {
                    this.CalculationEndField = value;
                    this.RaisePropertyChanged("CalculationEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CalculationStart {
            get {
                return this.CalculationStartField;
            }
            set {
                if ((this.CalculationStartField.Equals(value) != true)) {
                    this.CalculationStartField = value;
                    this.RaisePropertyChanged("CalculationStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NumberRecognizer.App.NumberRecognizerService.FitnessLog FinalPoolFitnessLog {
            get {
                return this.FinalPoolFitnessLogField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalPoolFitnessLogField, value) != true)) {
                    this.FinalPoolFitnessLogField = value;
                    this.RaisePropertyChanged("FinalPoolFitnessLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MultipleGenPool {
            get {
                return this.MultipleGenPoolField;
            }
            set {
                if ((this.MultipleGenPoolField.Equals(value) != true)) {
                    this.MultipleGenPoolField = value;
                    this.RaisePropertyChanged("MultipleGenPool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, NumberRecognizer.App.NumberRecognizerService.FitnessLog> MultiplePoolFitnessLog {
            get {
                return this.MultiplePoolFitnessLogField;
            }
            set {
                if ((object.ReferenceEquals(this.MultiplePoolFitnessLogField, value) != true)) {
                    this.MultiplePoolFitnessLogField = value;
                    this.RaisePropertyChanged("MultiplePoolFitnessLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NetworkFitness {
            get {
                return this.NetworkFitnessField;
            }
            set {
                if ((this.NetworkFitnessField.Equals(value) != true)) {
                    this.NetworkFitnessField = value;
                    this.RaisePropertyChanged("NetworkFitness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NetworkId {
            get {
                return this.NetworkIdField;
            }
            set {
                if ((this.NetworkIdField.Equals(value) != true)) {
                    this.NetworkIdField = value;
                    this.RaisePropertyChanged("NetworkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetworkName {
            get {
                return this.NetworkNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NetworkNameField, value) != true)) {
                    this.NetworkNameField = value;
                    this.RaisePropertyChanged("NetworkName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NumberRecognizer.App.NumberRecognizerService.NetworkStatusType Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FitnessLog", Namespace="http://schemas.datacontract.org/2004/07/NumberRecognizer.Cloud.Contract.Data")]
    public partial class FitnessLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<string, double> FinalPatternFittnessField;
        
        private System.Collections.ObjectModel.ObservableCollection<double> FitnessTrendField;
        
        private System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<double>> PatternTrendsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, double> FinalPatternFittness {
            get {
                return this.FinalPatternFittnessField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalPatternFittnessField, value) != true)) {
                    this.FinalPatternFittnessField = value;
                    this.RaisePropertyChanged("FinalPatternFittness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<double> FitnessTrend {
            get {
                return this.FitnessTrendField;
            }
            set {
                if ((object.ReferenceEquals(this.FitnessTrendField, value) != true)) {
                    this.FitnessTrendField = value;
                    this.RaisePropertyChanged("FitnessTrend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<double>> PatternTrends {
            get {
                return this.PatternTrendsField;
            }
            set {
                if ((object.ReferenceEquals(this.PatternTrendsField, value) != true)) {
                    this.PatternTrendsField = value;
                    this.RaisePropertyChanged("PatternTrends");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NetworkStatusType", Namespace="http://schemas.datacontract.org/2004/07/NumberRecognizer.Cloud.Contract.Data")]
    public enum NetworkStatusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotStarted = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Running = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ready = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainingImage", Namespace="http://schemas.datacontract.org/2004/07/NumberRecognizer.Cloud.Contract.Data")]
    public partial class TrainingImage : NumberRecognizer.App.NumberRecognizerService.RecognitionImage {
        
        private string PatternField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pattern {
            get {
                return this.PatternField;
            }
            set {
                if ((object.ReferenceEquals(this.PatternField, value) != true)) {
                    this.PatternField = value;
                    this.RaisePropertyChanged("Pattern");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecognitionImage", Namespace="http://schemas.datacontract.org/2004/07/NumberRecognizer.Cloud.Contract.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NumberRecognizer.App.NumberRecognizerService.TrainingImage))]
    public partial class RecognitionImage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int HeightField;
        
        private System.Collections.ObjectModel.ObservableCollection<double> ImageDataField;
        
        private int WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<double> ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberRecognitionResult", Namespace="http://schemas.datacontract.org/2004/07/NumberRecognizer.Cloud.Contract.Data")]
    public partial class NumberRecognitionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.NumberRecognitionResultItem> ItemsField;
        
        private string NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.NumberRecognitionResultItem> Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberRecognitionResultItem", Namespace="http://schemas.datacontract.org/2004/07/NumberRecognizer.Cloud.Contract.Data")]
    public partial class NumberRecognitionResultItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int NumericCharacterField;
        
        private System.Collections.Generic.Dictionary<char, double> ProbabilitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumericCharacter {
            get {
                return this.NumericCharacterField;
            }
            set {
                if ((this.NumericCharacterField.Equals(value) != true)) {
                    this.NumericCharacterField = value;
                    this.RaisePropertyChanged("NumericCharacter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<char, double> Probabilities {
            get {
                return this.ProbabilitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProbabilitiesField, value) != true)) {
                    this.ProbabilitiesField = value;
                    this.RaisePropertyChanged("Probabilities");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumberRecognizerService.INumberRecognizerService")]
    public interface INumberRecognizerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberRecognizerService/GetNetworks", ReplyAction="http://tempuri.org/INumberRecognizerService/GetNetworksResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.NetworkInfo>> GetNetworksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberRecognizerService/CreateNetwork", ReplyAction="http://tempuri.org/INumberRecognizerService/CreateNetworkResponse")]
        System.Threading.Tasks.Task<bool> CreateNetworkAsync(string networkName, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.TrainingImage> individualTrainingsData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberRecognizerService/CreateNetworkWithTrainingDataCopy", ReplyAction="http://tempuri.org/INumberRecognizerService/CreateNetworkWithTrainingDataCopyResp" +
            "onse")]
        System.Threading.Tasks.Task<bool> CreateNetworkWithTrainingDataCopyAsync(string networkName, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.TrainingImage> individualTrainingsData, int copyTraindataFromNetworkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberRecognizerService/DeleteNetwork", ReplyAction="http://tempuri.org/INumberRecognizerService/DeleteNetworkResponse")]
        System.Threading.Tasks.Task<bool> DeleteNetworkAsync(int networkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberRecognizerService/RecognizePhoneNumber", ReplyAction="http://tempuri.org/INumberRecognizerService/RecognizePhoneNumberResponse")]
        System.Threading.Tasks.Task<NumberRecognizer.App.NumberRecognizerService.NumberRecognitionResult> RecognizePhoneNumberAsync(int networkId, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.RecognitionImage> imageData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberRecognizerServiceChannel : NumberRecognizer.App.NumberRecognizerService.INumberRecognizerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberRecognizerServiceClient : System.ServiceModel.ClientBase<NumberRecognizer.App.NumberRecognizerService.INumberRecognizerService>, NumberRecognizer.App.NumberRecognizerService.INumberRecognizerService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NumberRecognizerServiceClient() : 
                base(NumberRecognizerServiceClient.GetDefaultBinding(), NumberRecognizerServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INumberRecognizerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberRecognizerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NumberRecognizerServiceClient.GetBindingForEndpoint(endpointConfiguration), NumberRecognizerServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberRecognizerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NumberRecognizerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberRecognizerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NumberRecognizerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberRecognizerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.NetworkInfo>> GetNetworksAsync() {
            return base.Channel.GetNetworksAsync();
        }
        
        public System.Threading.Tasks.Task<bool> CreateNetworkAsync(string networkName, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.TrainingImage> individualTrainingsData) {
            return base.Channel.CreateNetworkAsync(networkName, individualTrainingsData);
        }
        
        public System.Threading.Tasks.Task<bool> CreateNetworkWithTrainingDataCopyAsync(string networkName, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.TrainingImage> individualTrainingsData, int copyTraindataFromNetworkId) {
            return base.Channel.CreateNetworkWithTrainingDataCopyAsync(networkName, individualTrainingsData, copyTraindataFromNetworkId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteNetworkAsync(int networkId) {
            return base.Channel.DeleteNetworkAsync(networkId);
        }
        
        public System.Threading.Tasks.Task<NumberRecognizer.App.NumberRecognizerService.NumberRecognitionResult> RecognizePhoneNumberAsync(int networkId, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.App.NumberRecognizerService.RecognitionImage> imageData) {
            return base.Channel.RecognizePhoneNumberAsync(networkId, imageData);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INumberRecognizerService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INumberRecognizerService)) {
                return new System.ServiceModel.EndpointAddress("http://0d832919582344d9b6d490f5aca905d8.cloudapp.net/NumberRecognizerService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return NumberRecognizerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INumberRecognizerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return NumberRecognizerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INumberRecognizerService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_INumberRecognizerService,
        }
    }
}
