//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace NumberRecognizer.App.NumberRecognizerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumberRecognizerService.INumberRecognizerService")]
    public interface INumberRecognizerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberRecognizerService/GetNetworks", ReplyAction="http://tempuri.org/INumberRecognizerService/GetNetworksResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.Cloud.Contract.Data.NetworkInfo>> GetNetworksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberRecognizerService/CreateNetwork", ReplyAction="http://tempuri.org/INumberRecognizerService/CreateNetworkResponse")]
        System.Threading.Tasks.Task<bool> CreateNetworkAsync(string networkName, string username, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.Cloud.Contract.Data.TrainingImage> individualTrainingsData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberRecognizerService/CreateNetworkWithTrainingDataCopy", ReplyAction="http://tempuri.org/INumberRecognizerService/CreateNetworkWithTrainingDataCopyResp" +
            "onse")]
        System.Threading.Tasks.Task<bool> CreateNetworkWithTrainingDataCopyAsync(string networkName, string username, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.Cloud.Contract.Data.TrainingImage> individualTrainingsData, int copyTraindataFromNetworkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberRecognizerService/RecognizePhoneNumber", ReplyAction="http://tempuri.org/INumberRecognizerService/RecognizePhoneNumberResponse")]
        System.Threading.Tasks.Task<NumberRecognizer.Cloud.Contract.Data.NumberRecognitionResult> RecognizePhoneNumberAsync(int networkId, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.Cloud.Contract.Data.RecognitionImage> imageData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberRecognizerServiceChannel : NumberRecognizer.App.NumberRecognizerService.INumberRecognizerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberRecognizerServiceClient : System.ServiceModel.ClientBase<NumberRecognizer.App.NumberRecognizerService.INumberRecognizerService>, NumberRecognizer.App.NumberRecognizerService.INumberRecognizerService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NumberRecognizerServiceClient() : 
                base(NumberRecognizerServiceClient.GetDefaultBinding(), NumberRecognizerServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INumberRecognizerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberRecognizerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NumberRecognizerServiceClient.GetBindingForEndpoint(endpointConfiguration), NumberRecognizerServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberRecognizerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NumberRecognizerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberRecognizerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NumberRecognizerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberRecognizerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.Cloud.Contract.Data.NetworkInfo>> GetNetworksAsync() {
            return base.Channel.GetNetworksAsync();
        }
        
        public System.Threading.Tasks.Task<bool> CreateNetworkAsync(string networkName, string username, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.Cloud.Contract.Data.TrainingImage> individualTrainingsData) {
            return base.Channel.CreateNetworkAsync(networkName, username, individualTrainingsData);
        }
        
        public System.Threading.Tasks.Task<bool> CreateNetworkWithTrainingDataCopyAsync(string networkName, string username, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.Cloud.Contract.Data.TrainingImage> individualTrainingsData, int copyTraindataFromNetworkId) {
            return base.Channel.CreateNetworkWithTrainingDataCopyAsync(networkName, username, individualTrainingsData, copyTraindataFromNetworkId);
        }
        
        public System.Threading.Tasks.Task<NumberRecognizer.Cloud.Contract.Data.NumberRecognitionResult> RecognizePhoneNumberAsync(int networkId, System.Collections.ObjectModel.ObservableCollection<NumberRecognizer.Cloud.Contract.Data.RecognitionImage> imageData) {
            return base.Channel.RecognizePhoneNumberAsync(networkId, imageData);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INumberRecognizerService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INumberRecognizerService)) {
                return new System.ServiceModel.EndpointAddress("http://4574b9813eec49b598955c6a87e643e2.cloudapp.net/NumberRecognizerService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return NumberRecognizerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INumberRecognizerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return NumberRecognizerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INumberRecognizerService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_INumberRecognizerService,
        }
    }
}
